site_name: James MkDocs Insiders Playground
site_description: Playground for trying out all MkDocs Material features
site_url: https://sitename.example
theme:
  name: material
  features:
    - navigation.indexes # This gets rid of the extra "blog" entry under blog post navigation
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep orange
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy # This adds the month to the archive
      categories_allowed:
        - Holidays
        - News
  - tags:
      tags_file: blog/tags.md # This setting is not necessary with Insiders
  - meta

nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
  - Blog:
      - blog/index.md
      - blog/posts/myFirstBlogPost.md # Reference a specific post to appear in the Nav section
      - blog/randomPost.md # This post is not in the `posts` folder, so doesn't appear in the blog, but is on the nav
      - blog/tags.md # This one is just tags in the blog
  - Tags: tags.md # This page has tags for the whole site, not just the blog
