site_name: James MkDocs Insiders Playground
site_description: Playground for trying out all MkDocs Material features
site_url: https://sitename.example
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes # This gets rid of the extra "blog" entry under blog post navigation
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep orange
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy # This adds the month to the archive
      categories_allowed:
        - Holidays
        - News
      authors_profiles: true
      pagination_per_page: 2 # controls all pagination
      archive_pagination_per_page: 1 # or you can set a specific number for archive
      categories_pagination_per_page: 4 # or set a speicific number for the categories index
      blog_toc: true # This turns on the TOC for the index pages, which appears on the right
      # post_slugify:
      #   !!python/object/apply:ext.slugs.slugify # Also needed to do `export PYTHONPATH=$PYTHONPATH:$(pwd)/ext`
      #   kwds:
      #     short: true # This will change a slug to make it max 5 words, thanks to the custom logic
  - tags:
      tags_file: blog/tags.md # This setting is not necessary with Insiders
  - meta
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

extra:
  social:
    - icon: fontawesome/brands/mastodon
      name: squidfunk on Mastodon
      link: https://fosstodon.org/@squidfunk
    - icon: /fontawesome/regular/envelope
      name: send me an email
      link: mailto:<email-address>
    - icon: /material/mailbox
      name: contact us
      link: /contact

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
  - Blog:
      - blog/index.md
      - blog/posts/myFirstBlogPost.md # Reference a specific post to appear in the Nav section
      - blog/randomPost.md # This post is not in the `posts` folder, so doesn't appear in the blog, but is on the nav
      - blog/tags.md # This one is just tags in the blog
  - Tags: tags.md # This page has tags for the whole site, not just the blog
